#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Hannan\ProductReview\Console\Input;
use Hannan\ProductReview\Console\Kernel;
use Hannan\ProductReview\Console\Output;

$app = require_once __DIR__ . '/bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$status = $kernel->handle($input = new Input, new Output);

$kernel->terminate($input, $status);