#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Hannan\ProductReview\Console\Kernel;

$app = require_once __DIR__ . '/bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$options = getopt("", ["command:"]);

$command = $options['command'] ?? null;

$commands = [
    'migrate' => function () use ($kernel) {
        $kernel->migrate();
    },
    // Add more commands as needed
];

if (isset($commands[$command])) {
    $commands[$command]();
} else {
    echo "Command '$command' not found.\n";
}